### ISSUE TITLE
blake3 in msg ID?

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-buttwoo-spec#10]
Is there a reason why the msg ID should be the blake3 hash of the value+sig? Could the msg ID be the author ID plus sequence number? @arj03

**Comment by arj03** [comment]
With msg id using value and signature you are sure that the chain is unique (previous and parent field). But this could be an internal constraint. You could use the author (+parent) and seq to refer to a message within the chain such as in a tangle.

**Comment by staltz** [comment]
Ah, right, so blake3 hash is mostly useful for the previous field. And author+sequence can be like the most sensible URI pointing to a msg, e.g. in thread tangles.
