### ISSUE TITLE
Clarification about content

### ISSUE THREAD

**Issue by mycognosist** [ssbc/ssb-buttwoo-spec#7]
Just a quick question that came up for me while reading the spec:

Does the buttwoo spec have any constraints on the content beside the following?

> If not encrypted, content should be bipf encoded. If encrypted, a [ssb-bfe encrypted data format](https://github.com/ssb-ngi-pointer/ssb-bfe-spec#5-encrypted-data-formats) MUST be used.

So there's no limitation or specification on the shape of the content and the fields it may contain?

**Comment by arj03** [comment]
That is a really good question @mycognosist. Classic message has the [restriction](https://ssbc.github.io/scuttlebutt-protocol-guide/#message-format) that content must contain a type field with specific properties. I don't think we need to mandate that here. I pushed a comment that help clarify the content a bit. Hope that helps?

**Comment by mycognosist** [comment]
That's perfect. Thanks @arj03 :)
